// Logical UI groups for the Theme Creator's color picker fields.
// Each group maps Renoise element names to a user-facing category.
// Total: 70 Renoise elements across 6 groups, plus 14 hidden track palette slots.

export const GROUPS = [
  {
    id: 'backgrounds',
    icon: '🎨',
    label: 'Backgrounds & Surfaces',
    open: true,
    elements: [
      'Main_Back',
      'Body_Back',
      'Alternate_Main_Back',
      'Pattern_Default_Back',
      'Pattern_Highlighted_Back',
      'Pattern_CenterBar_Back',
      'Pattern_CenterBar_Back_StandBy',
      'Button_Back',
      'ValueBox_Back',
      'ToolTip_Back',
      'Midi_Mapping_Back',
    ],
  },
  {
    id: 'text',
    icon: '🔤',
    label: 'Text & Typography',
    open: true,
    elements: [
      'Main_Font',
      'Body_Font',
      'Strong_Body_Font',
      'Alternate_Main_Font',
      'Button_Font',
      'Selected_Button_Font',
      'Button_Highlight_Font',
      'ValueBox_Font',
      'ValueBox_Font_Icons',
      'Selection_Font',
      'StandBy_Selection_Font',
      'ToolTip_Font',
      'Midi_Mapping_Font',
      'Pattern_CenterBar_Font',
      'Pattern_CenterBar_Font_StandBy',
      'Pattern_Default_Font',
      'Pattern_Highlighted_Font',
    ],
  },
  {
    id: 'buttons',
    icon: '🔘',
    label: 'Buttons & Controls',
    open: false,
    elements: [
      'Selected_Button_Back',
      'Selection_Back',
      'Pattern_Selection',
      'Pattern_StandBy_Selection',
      'StandBy_Selection_Back',
      'Scrollbar',
      'Slider',
      'Folder',
    ],
  },
  {
    id: 'automation',
    icon: '📈',
    label: 'Automation Editor',
    open: false,
    elements: [
      'Automation_Grid',
      'Automation_Line_Edge',
      'Automation_Line_Fill',
      'Automation_Marker_Play',
      'Automation_Marker_Single',
      'Automation_Marker_Pair',
      'Automation_Marker_Diamond',
      'Automation_Point',
    ],
  },
  {
    id: 'pattern',
    icon: '🎹',
    label: 'Pattern Editor',
    open: false,
    elements: [
      'Pattern_Default_Font_Volume',
      'Pattern_Default_Font_Panning',
      'Pattern_Default_Font_Pitch',
      'Pattern_Default_Font_Delay',
      'Pattern_Default_Font_Global',
      'Pattern_Default_Font_Other',
      'Pattern_Default_Font_DspFx',
      'Pattern_Default_Font_Unused',
      'Pattern_Highlighted_Font_Volume',
      'Pattern_Highlighted_Font_Panning',
      'Pattern_Highlighted_Font_Pitch',
      'Pattern_Highlighted_Font_Delay',
      'Pattern_Highlighted_Font_Global',
      'Pattern_Highlighted_Font_Other',
      'Pattern_Highlighted_Font_DspFx',
      'Pattern_Highlighted_Font_Unused',
      'Pattern_PlayPosition_Back',
      'Pattern_PlayPosition_Font',
      'Pattern_Mute_State',
    ],
  },
  {
    id: 'vumeters',
    icon: '🔊',
    label: 'VU Meters',
    open: false,
    elements: [
      'VuMeter_Meter',
      'VuMeter_Meter_Low',
      'VuMeter_Meter_Middle',
      'VuMeter_Meter_High',
      'VuMeter_Peak',
      'VuMeter_Back_Normal',
      'VuMeter_Back_Clipped',
    ],
  },
];